import type { Metadata } from "next";
import Image from "next/image";
import LogoRocket from "@/assets/logo.svg";
import { axeAcessibilityReporter } from "@/utils/axeAcessibilityReporter";
import * as Dialog from "@radix-ui/react-dialog"

export const metadata: Metadata = {
  title: "Desenvolvendo uma web acessível",
  description: "Generated by create next app",
};

axeAcessibilityReporter();

export default function Home() {


  return (
    <>
      <header className="flex items-center justify-between max-w-5xl w-full mx-auto pt-6 ">
        <Image src={LogoRocket} width={286 / 2} alt="Rocketseat Blog" />

        <nav>
          <a href="https://github.com/thetunnes" className="text-[#8257e5]">
            <svg
              stroke="currentColor"
              fill="currentColor"
              strokeWidth="0"
              viewBox="0 0 512 512"
              height="28"
              width="28"
              xmlns="http://www.w3.org/2000/svg"
            >
              <path
                d="M256 32C132.3 32 32 134.9 32 261.7a229.3 229.3 0 0 0 153.2 217.9c1.4.3 2.6.4 3.8.4 8.3 0 11.5-6.1 11.5-11.4l-.3-39.1c-8.4 1.9-15.9 2.7-22.6 2.7-43.1 0-52.9-33.5-52.9-33.5-10.2-26.5-24.9-33.6-24.9-33.6-19.5-13.7-.1-14.1 1.4-14.1h.1c22.5 2 34.3 23.8 34.3 23.8 11.2 19.6 26.2 25.1 39.6 25.1a63 63 0 0 0 25.6-6c2-14.8 7.8-24.9 14.2-30.7-49.7-5.8-102-25.5-102-113.5 0-25.1 8.7-45.6 23-61.6a84.6 84.6 0 0 1 2.2-60.8s1.6-.5 5-.5c8.1 0 26.4 3.1 56.6 24.1a209.8 209.8 0 0 1 112.2 0c30.2-21 48.5-24.1 56.6-24.1 3.4 0 5 .5 5 .5a84.6 84.6 0 0 1 2.2 60.8 90.3 90.3 0 0 1 23 61.6c0 88.2-52.4 107.6-102.3 113.3 8 7.1 15.2 21.1 15.2 42.5 0 30.7-.3 55.5-.3 63 0 5.4 3.1 11.5 11.4 11.5 1.2 0 2.6-.1 4-.4A229.2 229.2 0 0 0 480 261.7C480 134.9 379.7 32 256 32z"
                stroke="none"
              />
            </svg>
          </a>
        </nav>
      </header>

      <main>
        <article className="text-zinc-300 flex flex-col items-center justify-between max-w-3xl w-full mx-auto pt-6">
          <h1 className="mb-5 text-2xl font-bold">
            Desenvolvendo uma web acessível
          </h1>

          <h2 className="text-xl font-bold">
            Protocolos e diretrizes orientam o desenvolvimento de tecnologias
            acessíveis
          </h2>

          <p className="mt-5">
            Acessibilidade se tornou uma tendência no ecossistema tecnológico
            mundial, diversas empresas passaram a adotar
          </p>
          <p className="mt-5">
            Acessibilidade se tornou uma tendência no ecossistema tecnológico
            mundial, diversas empresas passaram a adotar
          </p>
          <p className="mt-5">
            Acessibilidade se tornou uma tendência no ecossistema tecnológico
            mundial, diversas empresas passaram a adotar
          </p>

          <h3>O que é acessibilidade, afinal?</h3>
        </article>
      </main>

      <footer className="flex items-center justify-between max-w-5xl w-full mx-auto pt-6 ">
        <Image src={LogoRocket} width={286 / 2} alt="Blog da Rocketseat" />
        <nav aria-label="rodapé">
          <Dialog.Root>
            <Dialog.Trigger asChild>
            <button
            className="px-8 py-4 bg-[#202024] rounded-md text-[#9996DF]"
            type="button"
            aria-controls="modal1"
          >
            Termos de uso
          </button>
            </Dialog.Trigger>

            <Dialog.Portal>
              <Dialog.Overlay className="fixed inset-0 bg-black/75" />
              <Dialog.Content className="fixed top-1/2 left-1/2 -translate-x-1/2 -translate-y-1/2 bg-slate-100 p-10 rounded-md text-zinc-900">
                <Dialog.Title>Termos de uso</Dialog.Title>
                <Dialog.Description>Esses são os termos de uso.</Dialog.Description>
                <Dialog.Close asChild>
                  <button className="w-full py-3 px-2 mt-4 bg-[#8257e5] rounded-md text-slate-50 text-lg font-bold">Fechar</button>
                </Dialog.Close>
              </Dialog.Content>
            </Dialog.Portal>
          </Dialog.Root>
        </nav>
      </footer>

    </>
  );
}
